### ISSUE TITLE
DOC - Add Project title to README

### ISSUE THREAD

**Issue by funabab** [kwasu-ng/gdsckwasu-hacktoberfest21#27]
For now the project name is **Devllary**, it would be nice to have it somewhere in the README.

Also live link shouldn't be at the README bottom, it should be added to the top along side other navigation links (about, contributing  license etc). The link should probably state **Live Demo** (+1 if emoji is included)

**Comment by c-blaq** [comment]
Please assign me this task!

**Comment by Caleb335** [comment]
Sure. 

Go for it.

**Comment by funabab** [comment]
Nicely done @c-blaq 👍️ #33

**Comment by c-blaq** [comment]
Thanks @funabab
